### ISSUE TITLE
Mobile safari code samples don't wrap or show syntax highlighting

### ISSUE THREAD

**Issue by donjo** [denoland/deno-docs#207]
When loading the docs on mobile safari the syntax highlighting does not render and the spacing and text-wrapping of the code samples is not observed.

Example on the left is Safari's rendering and example on the right is Chrome (in a mobile viewport) 

<img width="1072" alt="Screenshot 2023-11-29 at 2 38 22 PM" src="https://github.com/denoland/deno-docs/assets/776987/e00e8287-ab5d-49ab-9b21-20bee807d612">

**Comment by joerick** [comment]
fwiw, i can recreate this in Chrome on desktop too. Sometimes happens, sometimes doesn't. Disabling cache in dev tools seems to increase the chances. Refreshing tends to fix it.

<img width="1957" alt="image" src="https://github.com/denoland/deno-docs/assets/1244307/7c568297-e3a3-4411-a319-97c81aebf7eb">

**Comment by kwhinnery** [comment]
This was being caused by a third party script for an embedded docs component - I have since removed it, and hopefully we should be good here now.
