### ISSUE TITLE
Subhosting "Quick Start" renders badly

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno-docs#219]
https://docs.deno.com/deploy/manual/subhosting#quick-start-example

This codeblock is not getting rendered properly (in a codeblock):
![Screenshot 2023-12-06 at 01 47 07](https://github.com/denoland/deno-docs/assets/13602871/dcb3b28b-4398-4369-856f-7e044bf19019)

**Comment by kwhinnery** [comment]
I finally reproduced this consistently, and discovered that this was related to a third party script I included on the site to embed the subhosting Rapidoc API explorer. I removed the script, and this issue should be gone now.
