### ISSUE TITLE
Broken links on deno.com

### ISSUE THREAD

**Issue by ElianCodes** [denoland/deno-docs#233]
### Problem description

Hey There! I ran into 2 broken links today. Since the deno.com homepage isn't open-source, I was asked to open an issue here.

- on https://deno.com/blog/build-crud-api-oak-denokv `https://deno.com/manualruntime/kv/operations` -> `https://deno.com/manual/runtime/kv/operations`
- on https://deno.com/learn/websites-apps `https://deno.land/manua/getting_started/web_frameworks`-> `https://deno.land/manual/getting_started/web_frameworks`

### Steps to reproduce

click on the links, I guess

### Expected behavior

Links should behave correctly

**Comment by kwhinnery** [comment]
these should be addressed now!
