### ISSUE TITLE
Add trace ops and other internal debugging functionality to manual 

### ISSUE THREAD

**Issue by ry** [denoland/deno-docs#467]
https://docs.deno.com/runtime/manual/basics/debugging_your_code

should also include internal debugging info
```
--strace-ops
--log-level=debug
--inspect
RUST_LOG=debug
```

Ask CLI team for other debugging functionality 
see also https://developer.chrome.com/docs/devtools/performance/reference

**Comment by thisisjofrank** [comment]
https://github.com/denoland/deno-docs/pull/562
