### ISSUE TITLE
<FOR ULTRA GOOD UX!!!> 🥰🥰🥰 There are significant improvements for documentation! This is just a real paradise!!! [API Reference] 😍😍😍

### ISSUE THREAD

**Issue by leonbakadorov** [denoland/deno-docs#480]
Documentation should be more visual and structured! We have significant improvements to the documentation section.

How can I contact the main person who is responsible for the https://deno.land/api section?

**Comment by crowlKats** [comment]
we are currently reworking the api reference

**Comment by leonbakadorov** [comment]
What is the planned release date for the new (reworked) version of the Reference API?

**Comment by rbetts** [comment]
This issue isn't actionable as written. We are happy to hear concrete suggestions for documentation improvements and also happy to review and merge focused PRs that are incremental improvements.
