### ISSUE TITLE
Remove `winget` install method

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno-docs#62]
It's very out of date: https://winget.run/pkg/DenoLand/Deno

**Comment by lilnasy** [comment]
[winget.run](https://github.com/winget-run/wingetdotrun) is an unmaintained community project not associated with winget. Its version list is not representative of what's available to the winget cli.

**Comment by kt3k** [comment]
@lilnasy Thanks for pointing it.

It looks like the package keeps updated in the actual registry https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+deno

I also found a up-to-date version of winget registry viewer, which list the latest version of Deno https://winstall.app/apps/DenoLand.Deno
