### ISSUE TITLE
[Basics/React]: Is note on Aleph using Preact correct?

### ISSUE THREAD

**Issue by rschristian** [denoland/deno-docs#78]
> Note: Fresh and Aleph.js provide a framework for developing React-like websites, but use an alternative foundational technology, Preact to provide a better, more performant experience.

https://deno.com/manual@v1.34.1/basics/react

I don't believe this is correct, given that [the very first issue in Aleph's tracker is requesting Preact support](https://github.com/alephjs/aleph.js/issues/1)?

**Comment by hashrock** [comment]
Yeah, looks like they don't support preact for now

https://alephjs.org/docs/framework/react
